Use ES6 arrow functions more
nodejs/installer pull request #32
Opened 2016-10-17 21:12 UTC by zdroid

Considering the installer is already ES6-friendly, let's get it to the higher level.

**Note:** It seems that using `() =>` syntax in `version.js` throws a type-related error (LTS and stable version don't get defined at the end), so I avoided arrow functions there.

2016-10-17 21:54 UTC, mikeal commented on lib/examples.js
> +module.exports = (callback) => {
You can actually leave off the parens when there's only a single argument ;)

2016-10-17 22:03 UTC, delvedor commented
You cannot use arrow functions in `versions.js` since arrow functions do not bind their own `this`.

This means that inside  `Versions.prototype.something` you cannot use `this.property`, because the arrow function (in this case) uses the global this and not the `Versions` one. :)

2016-10-18 06:07 UTC, zdroid commented on lib/examples.js
> +module.exports = (callback) => {
Well, people still prefer using `() =>` syntax as it looks more like a function and less like PHP or Ruby array. If needed, I can change single-argument functions to not have parens.

2016-10-18 06:07 UTC, zdroid commented
Thanks @delvedor. I really didn't know that. :smile:

2016-10-18 13:46 UTC, addaleax requested changes
Seems good for the most part!

2016-10-18 13:46 UTC, addaleax commented on browser.js
> +  start: () => {
This won’t work with `this`; but you’re lucky, there’s an even simpler way that works just fine: `start() {`

2016-10-18 13:46 UTC, addaleax commented on browser.js
> +  done: () => {
(ditto)

2016-10-18 17:27 UTC, zlatanvasovic commented on browser.js
> +  start: () => {
Fixed that now.

2016-10-18 17:51 UTC, addaleax approved these changes

2016-11-02 20:27 UTC, zdroid commented
Any news on this?

2016-11-10 21:09 UTC, zdroid commented
Any news on this?

2017-04-07 21:52 UTC, delvedor approved these changes

2017-04-07 21:53 UTC, delvedor commented
@addaleax @mikeal if is ok for you we can merge this.

2017-04-08 08:04 UTC, watilde approved these changes

2017-04-09 11:52 UTC, merged

2017-04-09 11:53 UTC, addaleax commented
@delvedor I’d say feel free to merge any PRs yourself :)